trigger:
  - azure-pipelines

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-dev
  - group: cpi-prod

# https://docs.microsoft.com/en-gb/azure/devops/pipelines/process/container-phases
resources:
  containers:
    - container: flashpipe
      image: engswee/flashpipe:3.0.0

jobs:
  - job: unit_test
    steps:
      - task: Maven@3
        displayName: 'Unit test'
        inputs:
          testRunTitle: 'Unit test'
          jdkVersionOption: '1.8'
          goals: 'test'
  - job: build
    container: flashpipe
    dependsOn: unit_test
    steps:
      # Upload/Update design time
      - bash: /usr/bin/flashpipe update artifact
        displayName: 'Update/Upload Groovy XML Transformation to design time'
        env:
          FLASHPIPE_TMN_HOST: $(dev-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
          FLASHPIPE_ARTIFACT_ID: GroovyXMLTransformation
          FLASHPIPE_ARTIFACT_NAME: "Groovy XML Transformation"
          FLASHPIPE_PACKAGE_ID: FlashPipeDemo
          FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo"
          FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
      - bash: /usr/bin/flashpipe update artifact
        displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
        env:
          FLASHPIPE_TMN_HOST: $(dev-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
          FLASHPIPE_ARTIFACT_ID: INVOIC02_to_Invoice_XML
          FLASHPIPE_ARTIFACT_NAME: "INVOIC02 to Invoice XML"
          FLASHPIPE_PACKAGE_ID: FlashPipeDemo
          FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo"
          FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
      # Deploy runtime
      - bash: /usr/bin/flashpipe deploy
        displayName: 'Deploy IFlows to runtime'
        env:
          FLASHPIPE_TMN_HOST: $(dev-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
          FLASHPIPE_ARTIFACT_IDS: GroovyXMLTransformation,INVOIC02_to_Invoice_XML
      # Publish Pipeline artifact
      - publish: $(System.DefaultWorkingDirectory)
        artifact: GitRepo
  - deployment: deploy_qa
    container: flashpipe
    dependsOn: build
    environment: cpi_dev
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: GitRepo
                path: $(Build.SourcesDirectory)/
            # Upload/Update design time
            - bash: /usr/bin/flashpipe update artifact
              displayName: 'Update/Upload Groovy XML Transformation to design time'
              env:
                FLASHPIPE_TMN_HOST: $(dev-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
                FLASHPIPE_ARTIFACT_ID: GroovyXMLTransformation_QA
                FLASHPIPE_ARTIFACT_NAME: "Groovy XML Transformation QA"
                FLASHPIPE_PACKAGE_ID: FlashPipeDemoQA
                FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo QA"
                FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
                FLASHPIPE_FILE_PARAM: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/parameters.prop"
                FLASHPIPE_FILE_MANIFEST: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/QA/MANIFEST.MF"
            - bash: /usr/bin/flashpipe update artifact
              displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
              env:
                FLASHPIPE_TMN_HOST: $(dev-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
                FLASHPIPE_ARTIFACT_ID: INVOIC02_to_Invoice_XML_QA
                FLASHPIPE_ARTIFACT_NAME: "INVOIC02 to Invoice XML QA"
                FLASHPIPE_PACKAGE_ID: FlashPipeDemoQA
                FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo QA"
                FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
                FLASHPIPE_FILE_PARAM: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/QA/parameters.prop"
                FLASHPIPE_FILE_MANIFEST: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/QA/MANIFEST.MF"
            # Deploy runtime
            - bash: /usr/bin/flashpipe deploy
              displayName: 'Deploy IFlows to runtime'
              env:
                FLASHPIPE_TMN_HOST: $(dev-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
                FLASHPIPE_ARTIFACT_IDS: GroovyXMLTransformation_QA,INVOIC02_to_Invoice_XML_QA
  - deployment: deploy_prod
    container: flashpipe
    dependsOn: deploy_qa
    environment: cpi_prod
    strategy:
      runOnce:
        deploy:
          steps:
            - download: none
            - task: DownloadPipelineArtifact@2
              inputs:
                artifact: GitRepo
                path: $(Build.SourcesDirectory)/
            # Upload/Update design time
            - bash: /usr/bin/flashpipe update artifact
              displayName: 'Update/Upload Groovy XML Transformation to design time'
              env:
                FLASHPIPE_TMN_HOST: $(prod-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(prod-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(prod-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(prod-client-secret)
                FLASHPIPE_ARTIFACT_ID: GroovyXMLTransformation
                FLASHPIPE_ARTIFACT_NAME: "Groovy XML Transformation"
                FLASHPIPE_PACKAGE_ID: FlashPipeDemo
                FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo"
                FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
                FLASHPIPE_FILE_PARAM: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation/PROD/parameters.prop"
            - bash: /usr/bin/flashpipe update artifact
              displayName: 'Update/Upload INVOIC02 to Invoice XML to design time'
              env:
                FLASHPIPE_TMN_HOST: $(prod-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(prod-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(prod-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(prod-client-secret)
                FLASHPIPE_ARTIFACT_ID: INVOIC02_to_Invoice_XML
                FLASHPIPE_ARTIFACT_NAME: "INVOIC02 to Invoice XML"
                FLASHPIPE_PACKAGE_ID: FlashPipeDemo
                FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo"
                FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML"
                FLASHPIPE_FILE_PARAM: "$(Build.SourcesDirectory)/FlashPipe Demo/INVOIC02_to_Invoice_XML/PROD/parameters.prop"
            # Deploy runtime
            - bash: /usr/bin/flashpipe deploy
              displayName: 'Deploy IFlows to runtime'
              env:
                FLASHPIPE_TMN_HOST: $(prod-host-tmn)
                FLASHPIPE_OAUTH_HOST: $(prod-oauth-host)
                FLASHPIPE_OAUTH_CLIENTID: $(prod-client-id)
                FLASHPIPE_OAUTH_CLIENTSECRET: $(prod-client-secret)
                FLASHPIPE_ARTIFACT_IDS: GroovyXMLTransformation,INVOIC02_to_Invoice_XML
