trigger:
  - azure-pipelines-single

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: cpi-dev

resources:
  containers:
    - container: flashpipe
      image: engswee/flashpipe:latest

jobs:
  - job: build
    container: flashpipe
    steps:
      # Upload/Update design time artifact
      - bash: flashpipe update artifact
        displayName: 'Update/Upload Groovy XML Transformation to design time'
        env:
          FLASHPIPE_TMN_HOST: $(dev-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
          FLASHPIPE_ARTIFACT_ID: GroovyXMLTransformation
          FLASHPIPE_ARTIFACT_NAME: "Groovy XML Transformation"
          FLASHPIPE_PACKAGE_ID: FlashPipeDemo
          FLASHPIPE_PACKAGE_NAME: "FlashPipe Demo"
          FLASHPIPE_DIR_ARTIFACT: "$(Build.SourcesDirectory)/FlashPipe Demo/Groovy XML Transformation"
      # Deploy to runtime
      - bash: flashpipe deploy
        displayName: 'Deploy Groovy XML Transformation to runtime'
        env:
          FLASHPIPE_TMN_HOST: $(dev-host-tmn)
          FLASHPIPE_OAUTH_HOST: $(dev-oauth-host)
          FLASHPIPE_OAUTH_CLIENTID: $(dev-client-id)
          FLASHPIPE_OAUTH_CLIENTSECRET: $(dev-client-secret)
          FLASHPIPE_ARTIFACT_IDS: GroovyXMLTransformation
