name: Tenant Snapshot Daily
on:
  schedule:
    - cron:  "30 14 * * *" # Runs at 14:30 UTC
jobs:
  take_snapshot:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:latest

    steps:
      - uses: actions/checkout@v4

      - name: 'Take a snapshot'
        uses: engswee/flashpipe-action/snapshot@v1
        with:
          tmn-host: equaliseit.it-cpi023.cfapps.eu20-001.hana.ondemand.com
          oauth-host: equaliseit.authentication.eu20.hana.ondemand.com
          oauth-clientid: ${{ secrets.DEV_CLIENT_ID }}
          oauth-clientsecret: ${{ secrets.DEV_CLIENT_SECRET }}
