name: Tenant Snapshot Daily
on:
  schedule:
    - cron:  "30 14 * * *" # Runs at 14:30 UTC
jobs:
  take_snapshot:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:3.0.0
    env:
      FLASHPIPE_TMN_HOST: equaliseit.it-cpi023.cfapps.eu20-001.hana.ondemand.com
      FLASHPIPE_OAUTH_HOST: equaliseit.authentication.eu20.hana.ondemand.com
      FLASHPIPE_OAUTH_CLIENTID: ${{ secrets.DEV_CLIENT_ID }}
      FLASHPIPE_OAUTH_CLIENTSECRET: ${{ secrets.DEV_CLIENT_SECRET }} 
    steps:
      - uses: actions/checkout@v3
      - name: 'Set FLASHPIPE_DIR_GIT_REPO for snapshot'
        run: |
          echo "FLASHPIPE_DIR_GIT_REPO=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      - name: 'Take a snapshot'
        run: /usr/bin/flashpipe snapshot
        shell: bash
      - name: Push changes
        run: git push
        shell: bash
        env:
          HOME: /root
