name: Sync APIM To Tenant
on:
  workflow_dispatch:
    inputs:
      directory:
        description: 'Target artifacts directory (relative from Git repository root)'
        default: 'FlashPipe Demo APIM'
        required: true
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:3.2.0
    steps:
      - uses: actions/checkout@v4
      - name: 'Sync APIProxy to tenant'
        uses: engswee/flashpipe-action/sync/apim@v1
        with:
          tmn-host: eu20apiportal.cfapps.eu20.hana.ondemand.com
          oauth-host: equaliseit.authentication.eu20.hana.ondemand.com
          oauth-clientid: ${{ secrets.APIPORTAL_OAUTH_CLIENTID }}
          oauth-clientsecret: ${{ secrets.APIPORTAL_OAUTH_CLIENTSECRET }}
          dir-artifacts-relative: ${{ github.event.inputs.directory }}
          target: tenant
