name: Sync Any IFlows from tenant

on:
  workflow_dispatch:
    inputs:
      packageId:
        description: 'Package ID'
        required: true
      directory:
        description: 'Target artifact directory (relative from Git repository root)'
        required: false
      includedIds:
        description: 'Included Ids (optional)'
        required: false
      excludedIds:
        description: 'Excluded Ids (optional)'
        required: false
      draft:
        description: 'Draft handling (optional) - SKIP (default value if empty), ADD, ERROR'
        type: choice
        options:
          - SKIP
          - ADD
          - ERROR
        required: false
      dirNaming:
        description: 'Naming convention for IFlow directories (optional) - ID (default value if empty), NAME'
        required: false
        type: choice
        options:
          - ID
          - NAME
      message:
        description: 'Commit message (optional)'
        required: false
jobs:
  sync:
    runs-on: ubuntu-latest
    container:
      image: engswee/flashpipe:3.0.0
    env:
      FLASHPIPE_TMN_HOST: equaliseit.it-cpi023.cfapps.eu20-001.hana.ondemand.com
      FLASHPIPE_OAUTH_HOST: equaliseit.authentication.eu20.hana.ondemand.com
      FLASHPIPE_OAUTH_CLIENTID: ${{ secrets.DEV_CLIENT_ID }}
      FLASHPIPE_OAUTH_CLIENTSECRET: ${{ secrets.DEV_CLIENT_SECRET }}     
    steps:
    - uses: actions/checkout@v4
    - name: 'Sync Any IFlows'
      run: flashpipe sync
      shell: bash
      env:
        FLASHPIPE_PACKAGE_ID: ${{ github.event.inputs.packageId }}
        FLASHPIPE_DIR_GIT_REPO: ${{ github.workspace }}
        FLASHPIPE_DIR_ARTIFACTS: ${{ github.workspace }}/${{ github.event.inputs.directory }}
        FLASHPIPE_IDS_INCLUDE: ${{ github.event.inputs.includedIds }}
        FLASHPIPE_IDS_EXCLUDE: ${{ github.event.inputs.excludedIds }}
        FLASHPIPE_DRAFT_HANDLING: ${{ github.event.inputs.draft }}
        FLASHPIPE_DIR_NAMING_TYPE: ${{ github.event.inputs.dirNaming }}
        FLASHPIPE_GIT_COMMIT_MSG: ${{ github.event.inputs.message }}
    - name: Push changes
      run: git push
      shell: bash
      env:
        HOME: /root
